CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL UNIQUE, role text NOT NULL DEFAULT 'editor' CHECK (role IN ('owner','editor')));
GRANT SELECT, INSERT, DELETE ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE FUNCTION public.apex_role() RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT role FROM public.user_roles WHERE lower(email) = lower(auth.jwt()->>'email') AND auth.jwt()->>'email_verified' IS DISTINCT FROM 'false' LIMIT 1 $$;
REVOKE ALL ON FUNCTION public.apex_role() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.apex_role() TO authenticated;
CREATE POLICY role_read ON public.user_roles FOR SELECT TO authenticated USING (lower(email)=lower(auth.jwt()->>'email') OR public.apex_role()='owner');
CREATE POLICY role_add ON public.user_roles FOR INSERT TO authenticated WITH CHECK (public.apex_role()='owner' AND role='editor');
CREATE POLICY role_remove ON public.user_roles FOR DELETE TO authenticated USING (public.apex_role()='owner' AND role='editor');
CREATE TABLE public.site_settings (id text PRIMARY KEY DEFAULT 'main', name text NOT NULL DEFAULT 'APEX', tagline text NOT NULL DEFAULT 'The summit is just the beginning.', description text NOT NULL DEFAULT 'A home for those who climb higher. Connect with the K2 Climbing community, find your next expedition, and reach the summit together.', discord_url text NOT NULL DEFAULT '', game_url text NOT NULL DEFAULT '', logo_url text NOT NULL DEFAULT '', eyebrow text NOT NULL DEFAULT 'BUILT FOR THE CLIMB', footer_text text NOT NULL DEFAULT 'Higher together.');
GRANT SELECT ON public.site_settings TO anon;
GRANT SELECT, INSERT, UPDATE ON public.site_settings TO authenticated;
GRANT ALL ON public.site_settings TO service_role;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY settings_read ON public.site_settings FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY settings_add ON public.site_settings FOR INSERT TO authenticated WITH CHECK (public.apex_role() IN ('owner','editor'));
CREATE POLICY settings_edit ON public.site_settings FOR UPDATE TO authenticated USING (public.apex_role() IN ('owner','editor')) WITH CHECK (public.apex_role() IN ('owner','editor'));
CREATE TABLE public.apps (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, description text NOT NULL DEFAULT '', category text NOT NULL DEFAULT 'Community', url text NOT NULL DEFAULT '', logo_url text NOT NULL DEFAULT '', icon text NOT NULL DEFAULT 'mountain', published boolean NOT NULL DEFAULT true, sort_order integer NOT NULL DEFAULT 0);
GRANT SELECT ON public.apps TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.apps TO authenticated;
GRANT ALL ON public.apps TO service_role;
ALTER TABLE public.apps ENABLE ROW LEVEL SECURITY;
CREATE POLICY apps_public ON public.apps FOR SELECT TO anon, authenticated USING (published);
CREATE POLICY apps_editor_read ON public.apps FOR SELECT TO authenticated USING (public.apex_role() IN ('owner','editor'));
CREATE POLICY apps_add ON public.apps FOR INSERT TO authenticated WITH CHECK (public.apex_role() IN ('owner','editor'));
CREATE POLICY apps_edit ON public.apps FOR UPDATE TO authenticated USING (public.apex_role() IN ('owner','editor')) WITH CHECK (public.apex_role() IN ('owner','editor'));
CREATE POLICY apps_remove ON public.apps FOR DELETE TO authenticated USING (public.apex_role() IN ('owner','editor'));