import { useEffect, useState, type FormEvent } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus, Trash2, Save, Upload, LogOut, Mountain, ShieldCheck } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { logStaff } from '@/lib/staff-log';
import { lovable } from '@/integrations/lovable';
import { useApexAuth } from '@/lib/apex-context';
import { getManagedApps, saveSiteSettings, saveManagedApp, deleteManagedApp, type ApexData } from '@/lib/apex.functions';
import { getAccess } from '@/lib/community.functions';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';

export function Logo({path,alt}:{path:string;alt:string}) {
 const {data}=useQuery({queryKey:['logo',path],enabled:!!path,queryFn:async()=>{const {data,error}=await supabase.storage.from('apex-logos').createSignedUrl(path,3600);if(error)throw error;return data.signedUrl;},staleTime:3000000});
 return data?<img className="custom-logo" src={data} alt={alt}/>:<Mountain/>;
}
// Google sign-in runs through Lovable's sign-in service, which only exists on Lovable hosting and
// only returns to addresses it knows. Anywhere else (such as localhost) fall back to the database's
// own Google sign-in, and say so plainly when that is not set up instead of landing on an error page.
async function googleSignIn() {
 const origin=window.location.origin;
 const hosted=await fetch('/~oauth/initiate',{method:'HEAD',redirect:'manual'}).then(r=>r.type==='opaqueredirect'||r.ok,()=>false);
 if(hosted){const r=await lovable.auth.signInWithOAuth('google',{redirect_uri:origin});if(r.error)throw r.error;return;}
 const {data,error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:origin,skipBrowserRedirect:true}});
 if(error||!data.url)throw error??new Error('Google sign-in failed.');
 const ready=await fetch(data.url,{redirect:'manual'}).then(r=>r.type==='opaqueredirect',()=>false);
 if(!ready)throw new Error(`Google sign-in is not set up for ${window.location.host}. Sign in with email and password here, or use Google on the live Apex site.`);
 window.location.href=data.url;
}
export function ApexEditor({open,onOpenChange,data}:{open:boolean;onOpenChange:(v:boolean)=>void;data:ApexData}) {
 const {user}=useApexAuth(); const qc=useQueryClient(); const [tab,setTab]=useState('Site');const [signup,setSignup]=useState(false);const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 const role=useQuery({queryKey:['role',user?.id],enabled:!!user,queryFn:async()=>{const {data,error}=await supabase.rpc('apex_role');if(error)throw error;return data;}});
 // When the site keeps its own data, admins sign in with the site's own Google sign-in (or are staff through
 // Discord) and the control room saves through the server; otherwise it is the database's editor account.
 const access=useQuery({queryKey:['access','editor'],queryFn:()=>getAccess()});
 const store=access.data?.store===true; const storeStaff=store&&access.data?.staff===true; const canEdit=storeStaff||!!role.data;
 const apps=useQuery({queryKey:['managed-apps',user?.id,storeStaff],enabled:open&&canEdit,queryFn:async()=>{if(store)return await getManagedApps()??[];const {data,error}=await supabase.from('apps').select('*').order('sort_order');if(error)throw error;return data;}});
 // Coming back from Google: say what happened.
 useEffect(()=>{const url=new URL(window.location.href);const result=url.searchParams.get('admin');if(!result)return;url.searchParams.delete('admin');window.history.replaceState(null,'',url);const text:Record<string,string>={denied:'That Google account is not on the admin list.',failed:'Google sign-in did not finish. Please try again.',unconfigured:'Google sign-in is not set up on this site yet.'};if(text[result]){setMessage(text[result]);onOpenChange(true);}},[onOpenChange]);
 async function google(){if(access.data?.google){window.location.href='/api/public/google/login';return;}if(store)throw new Error('Google sign-in is not set up on this site yet. Staff can link their Discord instead.');await googleSignIn();}
 async function signOut(){if(!store)logStaff('Admin signed out');await qc.cancelQueries();if(store)await fetch('/api/public/google/logout',{method:'POST'});else await supabase.auth.signOut();qc.clear();onOpenChange(false);}
 const editors=useQuery({queryKey:['editors',user?.id],enabled:open&&role.data==='owner',queryFn:async()=>{const {data,error}=await supabase.from('user_roles').select('*');if(error)throw error;return data;}});
 async function perform(action:()=>Promise<void>,logAs?:string){setBusy(true);setMessage('');try{await action();await qc.invalidateQueries();setMessage('Saved successfully.');if(logAs&&!store)logStaff(logAs);}catch(e){setMessage(e instanceof Error?e.message:'Something went wrong.');}finally{setBusy(false);}}
 async function auth(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setMessage('');try{const credentials={email:String(f.get('email')),password:String(f.get('password'))};const {error}=signup?await supabase.auth.signUp({...credentials,options:{emailRedirectTo:window.location.origin}}):await supabase.auth.signInWithPassword(credentials);if(error)throw error;setMessage(signup?'Check your email to confirm your account, then sign in.':'Signed in.');if(!signup)logStaff('Admin signed in');}catch(e){setMessage(e instanceof Error?e.message:'Sign-in failed.');}finally{setBusy(false);}}
 async function upload(file:File){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2097152)throw new Error('Choose a PNG, JPEG, or WebP logo under 2 MB.');const path=`${crypto.randomUUID()}.${file.type.split('/')[1]}`;const {error}=await supabase.storage.from('apex-logos').upload(path,file);if(error)throw error;return path;}
 async function saveSite(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await perform(async()=>{const file=f.get('logo') as File;const values=Object.fromEntries(['name','tagline','description','discord_url','game_url','eyebrow','footer_text'].map(k=>[k,String(f.get(k)??'')]));for(const k of ['discord_url','game_url'])if(values[k]&&!/^https:\/\//.test(values[k]))throw new Error('Links must start with https://');if(store){const v=(k:string)=>values[k]??'';await saveSiteSettings({data:{name:v('name'),eyebrow:v('eyebrow'),tagline:v('tagline'),description:v('description'),discord_url:v('discord_url'),game_url:v('game_url'),footer_text:v('footer_text'),remove_logo:!!f.get('remove_logo')}});return;}const logo_url=file?.size?await upload(file):f.get('remove_logo')? '':data.settings.logo_url;const {error}=await supabase.from('site_settings').update({...values,logo_url}).eq('id','main');if(error)throw error;},'Site settings saved');}
 async function saveApp(e:FormEvent<HTMLFormElement>,id?:string){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);await perform(async()=>{const file=f.get('logo') as File;const current=apps.data?.find(a=>a.id===id);const url=String(f.get('url')??'');if(url&&!/^https:\/\//.test(url))throw new Error('Links must start with https://');if(store){await saveManagedApp({data:{id,name:String(f.get('name')),description:String(f.get('description')??''),category:String(f.get('category')),url,sort_order:Number(f.get('sort_order')),published:f.get('published')==='on',remove_logo:!!f.get('remove_logo')}});if(!id)form.reset();return;}const values={name:String(f.get('name')),description:String(f.get('description')),category:String(f.get('category')),url,sort_order:Number(f.get('sort_order')),published:f.get('published')==='on',logo_url:file?.size?await upload(file):f.get('remove_logo')?'':current?.logo_url??''};const result=id?await supabase.from('apps').update(values).eq('id',id):await supabase.from('apps').insert(values);if(result.error)throw result.error;if(!id)form.reset();},`App ${id?'edited':'added'}: ${String(f.get('name'))}`);}
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="editor-dialog"><DialogTitle className="editor-title"><ShieldCheck/> {user||storeStaff?'Apex control room':'Admin access'}</DialogTitle><DialogDescription>{user||storeStaff?(access.data?.admin?`Signed in as ${access.data.admin}.`:'Your basecamp, your way.'):'For the Apex owner and authorized editors.'}</DialogDescription>
 {!user&&!storeStaff?<div><Button variant="outline" className="google-button" disabled={busy||access.isLoading} onClick={async()=>{setBusy(true);setMessage('');try{await google();}catch(e){setMessage(e instanceof Error?e.message:'Google sign-in failed.');}finally{setBusy(false);}}}>Continue with Google</Button>{store?<p className="access-note">Use the Google account on the admin list. Staff with a Discord staff role can link Discord at the top of the page instead.</p>:<><div className="auth-divider">or use email</div><form onSubmit={auth} className="editor-form"><label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Password<input name="password" type="password" minLength={8} required autoComplete={signup?'new-password':'current-password'}/></label><Button disabled={busy} type="submit">{signup?'Create account':'Sign in'}</Button></form><Button variant="link" onClick={()=>{setSignup(!signup);setMessage('')}}>{signup?'Already have an account? Sign in':'Create an account'}</Button></>}</div>:<><div className="editor-tabs">{canEdit&&['Site','Apps',...(role.data==='owner'?['Editors']:[])].map(t=><Button key={t} variant={tab===t?'default':'ghost'} onClick={()=>setTab(t)}>{t}</Button>)}{(user||access.data?.admin)&&<Button variant="ghost" size="icon" title="Sign out" aria-label="Sign out" onClick={signOut}><LogOut/></Button>}</div>{!storeStaff&&role.isLoading?<p>Checking access…</p>:!canEdit?<p className="access-note">This account doesn’t have editing access. Ask the Apex owner to add your email.</p>:<>
 {tab==='Site'&&<form className="editor-form" onSubmit={saveSite} key={data.settings.name+data.settings.tagline}>{([['name','Server name'],['eyebrow','Heading label'],['tagline','Headline'],['description','Description'],['discord_url','Discord invite link'],['game_url','K2 Climbing game link'],['footer_text','Footer text']] as const).map(([k,label])=><label key={k}>{label}<input name={k} defaultValue={String(data.settings[k as keyof typeof data.settings])} required={['name','tagline'].includes(k)} maxLength={k==='description'?500:200}/></label>)}{!store&&<label className="upload-label"><Upload/> Server logo<input type="file" name="logo" accept="image/png,image/jpeg,image/webp"/></label>}<label className="check-label"><input type="checkbox" name="remove_logo"/>Remove custom logo</label><Button type="submit" disabled={busy}><Save/>Save site</Button></form>}
 {tab==='Apps'&&<div className="manage-apps">{apps.data?.map(app=><form className="app-edit" key={app.id} onSubmit={e=>saveApp(e,app.id)}><AppFields app={app} upload={!store}/><div className="form-actions"><Button disabled={busy} type="submit"><Save/>Save app</Button><Button variant="ghost" size="icon" type="button" title="Delete app" aria-label={`Delete ${app.name}`} onClick={()=>{if(confirm(`Delete ${app.name}?`))void perform(async()=>{if(store){await deleteManagedApp({data:app.id});return;}const {error}=await supabase.from('apps').delete().eq('id',app.id);if(error)throw error;},`App deleted: ${app.name}`);}}><Trash2/></Button></div></form>)}<form className="app-edit" onSubmit={e=>saveApp(e)}><h3>New app</h3><AppFields upload={!store}/><Button type="submit" disabled={busy}><Plus/>Add app</Button></form></div>}
 {tab==='Editors'&&<div><form className="editor-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void perform(async()=>{const {error}=await supabase.from('user_roles').insert({email:String(f.get('email')).trim().toLowerCase(),role:'editor'});if(error)throw error;},`Editor added: ${String(f.get('email')).trim().toLowerCase()}`);}}><label>Editor email<input type="email" name="email" required/></label><Button type="submit" disabled={busy}><Plus/>Add editor</Button></form><div className="editor-list">{editors.data?.map(editor=><div key={editor.id}><span>{editor.email}<small>{editor.role}</small></span>{editor.role==='editor'&&<Button aria-label={`Remove ${editor.email}`} title="Remove editor" variant="ghost" size="icon" onClick={()=>void perform(async()=>{const {error}=await supabase.from('user_roles').delete().eq('id',editor.id);if(error)throw error;},`Editor removed: ${editor.email}`)}><Trash2/></Button>}</div>)}</div></div>}
 </>}</>}{message&&<p role="status" className="editor-message">{message}</p>}</DialogContent></Dialog>;
}
function AppFields({app,upload=true}:{app?:ApexData['apps'][number];upload?:boolean}){return <div className="editor-form"><label>App name<input name="name" required defaultValue={app?.name}/></label><label>Description<input name="description" defaultValue={app?.description}/></label><div className="form-columns"><label>Category<select name="category" defaultValue={app?.category??'Community'}>{['Game','Community','Applications','Resources'].map(c=><option key={c}>{c}</option>)}</select></label><label>Order<input type="number" name="sort_order" defaultValue={app?.sort_order??0}/></label></div><label>Destination link<input name="url" type="url" defaultValue={app?.url} placeholder="https://"/></label>{upload&&<label>Logo<input type="file" name="logo" accept="image/png,image/jpeg,image/webp"/></label>}<div className="form-columns"><label className="check-label"><input type="checkbox" name="published" defaultChecked={app?.published??true}/>Visible</label><label className="check-label"><input type="checkbox" name="remove_logo"/>Remove logo</label></div></div>}
