/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as ExpeditionsRouteImport } from './routes/expeditions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApplyFormIdRouteImport } from './routes/apply_.$formId'
import { Route as ApplyReviewsRouteImport } from './routes/apply_.reviews'
import { Route as ReportsReviewsRouteImport } from './routes/reports_.reviews'
import { Route as ApiPublicDiscordCallbackRouteImport } from './routes/api/public/discord/callback'
import { Route as ApiPublicDiscordLoginRouteImport } from './routes/api/public/discord/login'
import { Route as ApiPublicDiscordLogoutRouteImport } from './routes/api/public/discord/logout'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google/callback'
import { Route as ApiPublicGoogleLoginRouteImport } from './routes/api/public/google/login'
import { Route as ApiPublicGoogleLogoutRouteImport } from './routes/api/public/google/logout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditionsRoute = ExpeditionsRouteImport.update({
  id: '/expeditions',
  path: '/expeditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyFormIdRoute = ApplyFormIdRouteImport.update({
  id: '/apply_/$formId',
  path: '/apply/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyReviewsRoute = ApplyReviewsRouteImport.update({
  id: '/apply_/reviews',
  path: '/apply/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReviewsRoute = ReportsReviewsRouteImport.update({
  id: '/reports_/reviews',
  path: '/reports/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordCallbackRoute =
  ApiPublicDiscordCallbackRouteImport.update({
    id: '/api/public/discord/callback',
    path: '/api/public/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiscordLoginRoute = ApiPublicDiscordLoginRouteImport.update({
  id: '/api/public/discord/login',
  path: '/api/public/discord/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordLogoutRoute = ApiPublicDiscordLogoutRouteImport.update({
  id: '/api/public/discord/logout',
  path: '/api/public/discord/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleLoginRoute = ApiPublicGoogleLoginRouteImport.update({
  id: '/api/public/google/login',
  path: '/api/public/google/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleLogoutRoute = ApiPublicGoogleLogoutRouteImport.update({
  id: '/api/public/google/logout',
  path: '/api/public/google/logout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/expeditions': typeof ExpeditionsRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/terms': typeof TermsRoute
  '/apply/$formId': typeof ApplyFormIdRoute
  '/apply/reviews': typeof ApplyReviewsRoute
  '/reports/reviews': typeof ReportsReviewsRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/login': typeof ApiPublicDiscordLoginRoute
  '/api/public/discord/logout': typeof ApiPublicDiscordLogoutRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/google/login': typeof ApiPublicGoogleLoginRoute
  '/api/public/google/logout': typeof ApiPublicGoogleLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/expeditions': typeof ExpeditionsRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/terms': typeof TermsRoute
  '/apply/$formId': typeof ApplyFormIdRoute
  '/apply/reviews': typeof ApplyReviewsRoute
  '/reports/reviews': typeof ReportsReviewsRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/login': typeof ApiPublicDiscordLoginRoute
  '/api/public/discord/logout': typeof ApiPublicDiscordLogoutRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/google/login': typeof ApiPublicGoogleLoginRoute
  '/api/public/google/logout': typeof ApiPublicGoogleLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/expeditions': typeof ExpeditionsRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/terms': typeof TermsRoute
  '/apply_/$formId': typeof ApplyFormIdRoute
  '/apply_/reviews': typeof ApplyReviewsRoute
  '/reports_/reviews': typeof ReportsReviewsRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/login': typeof ApiPublicDiscordLoginRoute
  '/api/public/discord/logout': typeof ApiPublicDiscordLogoutRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
  '/api/public/google/login': typeof ApiPublicGoogleLoginRoute
  '/api/public/google/logout': typeof ApiPublicGoogleLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/expeditions'
    | '/privacy'
    | '/reports'
    | '/rules'
    | '/terms'
    | '/apply/$formId'
    | '/apply/reviews'
    | '/reports/reviews'
    | '/api/public/discord/callback'
    | '/api/public/discord/login'
    | '/api/public/discord/logout'
    | '/api/public/google/callback'
    | '/api/public/google/login'
    | '/api/public/google/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/expeditions'
    | '/privacy'
    | '/reports'
    | '/rules'
    | '/terms'
    | '/apply/$formId'
    | '/apply/reviews'
    | '/reports/reviews'
    | '/api/public/discord/callback'
    | '/api/public/discord/login'
    | '/api/public/discord/logout'
    | '/api/public/google/callback'
    | '/api/public/google/login'
    | '/api/public/google/logout'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/expeditions'
    | '/privacy'
    | '/reports'
    | '/rules'
    | '/terms'
    | '/apply_/$formId'
    | '/apply_/reviews'
    | '/reports_/reviews'
    | '/api/public/discord/callback'
    | '/api/public/discord/login'
    | '/api/public/discord/logout'
    | '/api/public/google/callback'
    | '/api/public/google/login'
    | '/api/public/google/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  ExpeditionsRoute: typeof ExpeditionsRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportsRoute: typeof ReportsRoute
  RulesRoute: typeof RulesRoute
  TermsRoute: typeof TermsRoute
  ApplyFormIdRoute: typeof ApplyFormIdRoute
  ApplyReviewsRoute: typeof ApplyReviewsRoute
  ReportsReviewsRoute: typeof ReportsReviewsRoute
  ApiPublicDiscordCallbackRoute: typeof ApiPublicDiscordCallbackRoute
  ApiPublicDiscordLoginRoute: typeof ApiPublicDiscordLoginRoute
  ApiPublicDiscordLogoutRoute: typeof ApiPublicDiscordLogoutRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
  ApiPublicGoogleLoginRoute: typeof ApiPublicGoogleLoginRoute
  ApiPublicGoogleLogoutRoute: typeof ApiPublicGoogleLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditions': {
      id: '/expeditions'
      path: '/expeditions'
      fullPath: '/expeditions'
      preLoaderRoute: typeof ExpeditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply_/$formId': {
      id: '/apply_/$formId'
      path: '/apply/$formId'
      fullPath: '/apply/$formId'
      preLoaderRoute: typeof ApplyFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply_/reviews': {
      id: '/apply_/reviews'
      path: '/apply/reviews'
      fullPath: '/apply/reviews'
      preLoaderRoute: typeof ApplyReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports_/reviews': {
      id: '/reports_/reviews'
      path: '/reports/reviews'
      fullPath: '/reports/reviews'
      preLoaderRoute: typeof ReportsReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/callback': {
      id: '/api/public/discord/callback'
      path: '/api/public/discord/callback'
      fullPath: '/api/public/discord/callback'
      preLoaderRoute: typeof ApiPublicDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/login': {
      id: '/api/public/discord/login'
      path: '/api/public/discord/login'
      fullPath: '/api/public/discord/login'
      preLoaderRoute: typeof ApiPublicDiscordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/logout': {
      id: '/api/public/discord/logout'
      path: '/api/public/discord/logout'
      fullPath: '/api/public/discord/logout'
      preLoaderRoute: typeof ApiPublicDiscordLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/login': {
      id: '/api/public/google/login'
      path: '/api/public/google/login'
      fullPath: '/api/public/google/login'
      preLoaderRoute: typeof ApiPublicGoogleLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google/logout': {
      id: '/api/public/google/logout'
      path: '/api/public/google/logout'
      fullPath: '/api/public/google/logout'
      preLoaderRoute: typeof ApiPublicGoogleLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  ExpeditionsRoute: ExpeditionsRoute,
  PrivacyRoute: PrivacyRoute,
  ReportsRoute: ReportsRoute,
  RulesRoute: RulesRoute,
  TermsRoute: TermsRoute,
  ApplyFormIdRoute: ApplyFormIdRoute,
  ApplyReviewsRoute: ApplyReviewsRoute,
  ReportsReviewsRoute: ReportsReviewsRoute,
  ApiPublicDiscordCallbackRoute: ApiPublicDiscordCallbackRoute,
  ApiPublicDiscordLoginRoute: ApiPublicDiscordLoginRoute,
  ApiPublicDiscordLogoutRoute: ApiPublicDiscordLogoutRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
  ApiPublicGoogleLoginRoute: ApiPublicGoogleLoginRoute,
  ApiPublicGoogleLogoutRoute: ApiPublicGoogleLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
